<?php

namespace mmarchio\NodeManagerBundle\Repository;

/**
 * node_test_nodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class node_test_nodeRepository extends \Doctrine\ORM\EntityRepository
{
}
